### ISSUE TITLE
Users are not well informed that something went wrong (of underlying code errors)

### ISSUE THREAD

**Issue by hellolucas** [Computable-Finance/CoFiX-Web-User-Interface#13]
On CoFi tab, when Depositing XToken, nothing happens. Button goes into "Pending" but no transaction is performed. 

XT-2 for the pair ETH/HBTC used.

![ezgif-7-f148652e7ce6](https://user-images.githubusercontent.com/17125002/95739207-1116ef00-0cbd-11eb-9a77-cbaaf176d6d2.gif)

**Comment by colourful-land** [comment]
There is an underlying error (occurred after the hourglass animation stopped) which was ignored by the UI. The UI developer asked for a design proposal to handle errors. Such error is expected to happen a lot in the coming weeks.

I adviced the UI developer to (as a quick fix) display a "soemthing went wrong" with a link that can show the full error. I believe she has implemented this. So please reconduct this and provide a updated design to replace this quick fix design I adviced.

**Comment by foxgem** [comment]
Current UI has already implement the feature suggested in comment, an error message will be shown if something goes wrong.

So, I will close this issue.
