### ISSUE TITLE
CoFi tab, doesn't display Token and CoFi token amount until pair is selected

### ISSUE THREAD

**Issue by hboon** [Computable-Finance/CoFiX-Web-User-Interface#16]
If you go to CoFi tab, tap on the pair selector and choose the appropriate one, the amount of XTokens (XT-1 or XT-2) you have deposited will be displayed. You have to tap on the pair selector and choose even if you have ETH/USDT

**Comment by foxgem** [comment]
This issue is a global issue for all inputs. And some of them should be fixed and included in this commit 19b4215618fcf2dcf082759eb55470be66062a4f . Others will be fixed soon.
