### ISSUE TITLE
Need a default token icon for the token inputted by user. 

### ISSUE THREAD

**Issue by foxgem** [Computable-Finance/CoFiX-Web-User-Interface#163]
Uniswap is open for those tokens not in its default list: user could select them by inputting the token's address. We are considering to add this feature in CoFiX Web UI.

However, not like the tokens in list, frontend could not know the logo of that token inputted by user. So, need a default token icon for this case.

**Comment by colourfreak** [comment]
That could be this one: 
https://zpl.io/a8XpEdE

<img width="653" alt="Screenshot 2020-12-15 at 08 59 58" src="https://user-images.githubusercontent.com/51817359/102187207-f8d97100-3eb3-11eb-9f84-95f73ec0ea3e.png">

---
or this one:
https://zpl.io/a8XpEdE
<img width="635" alt="Screenshot 2020-12-15 at 09 00 01" src="https://user-images.githubusercontent.com/51817359/102187193-f545ea00-3eb3-11eb-98f6-71479eee9766.png">

**Comment by foxgem** [comment]
It has been included in commit: ad5ea06470a833e036c5ccfff95ba88e2d5bdfcd .
