### ISSUE TITLE
UI design for WalletConnect

### ISSUE THREAD

**Issue by foxgem** [Computable-Finance/CoFiX-Web-User-Interface#167]
CoFiX plans to support WalletConnect (#165), so new ui design is needed.

**Comment by colourfreak** [comment]
Empty State
![Swap_Desktop_Connect_to_Clear](https://user-images.githubusercontent.com/51817359/105176434-8cdad000-5b25-11eb-843f-200841d2d29e.jpg)

Connected
![Swap_Desktop_Connect_to_Connected](https://user-images.githubusercontent.com/51817359/105176442-8fd5c080-5b25-11eb-8132-2c152bd2ed99.jpg)

Hover Over
![Swap_Desktop_Connect_to_Hover](https://user-images.githubusercontent.com/51817359/105176448-9106ed80-5b25-11eb-8896-bb143c6d1cc6.jpg)

Code
![Swap_Desktop_Connect_to_WalletConnect](https://user-images.githubusercontent.com/51817359/105176455-92d0b100-5b25-11eb-86ca-ade12bddbc97.jpg)

-----

Mobile 1
![Swap_Mobile_Connect_to](https://user-images.githubusercontent.com/51817359/105176457-93694780-5b25-11eb-8789-81dbc6b111b0.jpg)
Mobile 2
![Swap_Mobile_WalletConnect](https://user-images.githubusercontent.com/51817359/105176459-9401de00-5b25-11eb-94a2-b33d2a6fd485.jpg)

**Comment by colourfreak** [comment]
Zeplin:
https://zpl.io/adlExoE
https://zpl.io/a8Xxldw

**Comment by foxgem** [comment]
Close it because of #165 , a link between these two issues will be created.
