### ISSUE TITLE
after the user newly connected to Metamask, the "Max" button can't provide the user with their balance.

### ISSUE THREAD

**Issue by colourful-land** [Computable-Finance/CoFiX-Web-User-Interface#25]
This happens only if the user uses the "Connect to Wallet" button to connect to Metamask - it is not reporducible if the user is already connected to Metamask.
--
Observe this error which might have caused the bug:

src/app/service/cofix.service.ts: async getERC20Balance is called before the user logins to Metamask

Reproduce:

1. Log out of your current Metamask session (if not already)
2. Access cofix site (locally served)
http://localhost:8100/#/
3. Hit "Connect Wallet" - MetaMask pops up asking to login - don't login yet
4. At this point, `getERC20Balance` is fired without any valid address, `this.currentAccount` is undefined, causing a call revert exception

**Comment by foxgem** [comment]
Max btn will not be shown if user's balance could not be gotten.

**Comment by colourful-land** [comment]
> Max btn will not be shown if user's balance could not be gotten.

Well that is better then before.

We also need the max button to be availble once the user connects to Metamask, and it's not happening (using the code checked out an hour ago)
![Captura del escritorio de 14-10-20 12:06:40 mp4](https://user-images.githubusercontent.com/548435/95932435-94e4ee80-0e17-11eb-969e-2582161cf211.gif)

**Comment by foxgem** [comment]
OMG, init event is not fired after connecting wallet is done for current page. We will fix it soon.

**Comment by colourful-land** [comment]
I tested again and it seems working now did you fix it?
