### ISSUE TITLE
CoFiX挖矿 授权成功后按钮不消失

### ISSUE THREAD

**Issue by wqf512812** [Computable-Finance/CoFiX-Web-User-Interface#26]
CoFiX挖矿 授权成功后 授权按钮不消失 刷新页面才消失
![image](https://user-images.githubusercontent.com/72646718/95845795-35d29b80-0d7d-11eb-8b05-d5a8e56b305c.png)

**Comment by foxgem** [comment]
在授权成功之后，未重新获取按钮的授权状态。并且这个问题跟 #10 也有关联。
