### ISSUE TITLE
Cofix can't process  HBTC balance without losing precision

### ISSUE THREAD

**Issue by zhangzhongnan928** [Computable-Finance/CoFiX-Web-User-Interface#29]
|The correct balance | The balance reported by cofix|
|--|--|
|![IMG_5071](https://user-images.githubusercontent.com/33795543/95858593-0cc80000-0da9-11eb-8249-1d3d0446b88e.jpg) |![IMG_5073](https://user-images.githubusercontent.com/33795543/95858626-16516800-0da9-11eb-8d56-80f4ef84c38d.PNG)
|

**Comment by zhangzhongnan928** [comment]
![IMG_5103](https://user-images.githubusercontent.com/33795543/96051596-9837b300-0ec7-11eb-9292-1b40aaa9e2cf.jpg)

in the latest version

**Comment by foxgem** [comment]
It is a display issue of data, and fixed now.
