### ISSUE TITLE
Take care of Meta Title and Meta Description

### ISSUE THREAD

**Issue by colourfreak** [Computable-Finance/CoFiX-Web-User-Interface#32]
Cofix has just appeared on Google. Take care of Meta tags. 

<img width="951" alt="Screenshot 2020-10-13 at 19 23 20" src="https://user-images.githubusercontent.com/51817359/95894706-c31bed00-0d89-11eb-97a4-7d33571db0e8.png">

**Comment by foxgem** [comment]
Where I can get these text contents? Then I can update it in page. Or PR is great, I can merge it.

**Comment by colourfreak** [comment]
Title: "CoFiX: The most efficient On-Chain Market Making"
Description: "CoFiX is the most efficient token swap app on Ethereum. Trade tokens with the smallest spread, get rewarded with ETH dividends."

@hellolucas @zhangzhongnan928 @AW-STJ Do you have anything better in mind?

**Comment by abcfy2** [comment]
I've added some meta tags for this. This issue should be fixed.

**Comment by abcfy2** [comment]
Twitter share result:

![image](https://user-images.githubusercontent.com/5327677/95959107-a38dce80-0e34-11eb-844f-f9f7c4b891ea.png)

**Comment by colourfreak** [comment]
What is the size of Twitter Card graphic?

**Comment by abcfy2** [comment]
https://github.com/Computable-Finance/CoFiX-Web-User-Interface/blob/a461e8eb3074e402be14342c2cc6cdce7151ab52/src/index.html#L48-L51

After deploy to `cofix.io`, this image would be: `https://www.cofix.io/white/assets/images/logo.png` ![](https://www.cofix.io/white/assets/images/logo.png)

**Comment by AW-STJ** [comment]
> Title: "CoFiX: The most efficient On-Chain Market Making"
> Description: "CoFiX is the most efficient token swap app on Ethereum. Trade tokens with the smallest spread, get rewarded with ETH dividends."

Description: "CoFiX is the most efficient token swap app on Ethereum. Trade tokens with the smallest spread. Get ETH dividends for adding liquidity"
