### ISSUE TITLE
Wallet shows disconnected after a transaction

### ISSUE THREAD

**Issue by gnostix** [Computable-Finance/CoFiX-Web-User-Interface#37]
The wallet was connected and liquidity was added. However, the next day throws a JS exception and the wallet cannot connect anymore and therefore no access to my funds.

![Screenshot 2020-10-14 at 12 07 35 PM](https://user-images.githubusercontent.com/6529033/95968354-002dc100-0e16-11eb-83a0-dbb006666032.png)

**Comment by foxgem** [comment]
it seemed that not the version generated by this repo. metamask.js is an old version of cofix frontend, the version under development can be visit here: https://www.cofix.io/white , when it is ready, it will replace the old one and can be visit with https://www.cofix.io.
